version: '3.1'

networks:
  bookshelf:
    driver: bridge


services:

  database:
    image: postgres:13.4-alpine
    container_name: database
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelf
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./dbdata:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - bookshelf
    
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - bookshelf

  backend:
    image: kusumaningrat16/nodejs-bookshelf:v1
    container_name: nodejs-bookshelf
    restart: always
    ports:
      - 10000:5000
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: bookshelf
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - bookshelf

