name: 'Testing'
run-name: ${{ github.actor }} is learning Github Actions
on: 
 push:
    branches:
        - dev
        - main

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v3
      
         - name: Setup Docker buildx
           id: buildx
           uses: docker/setup-buildx-action@v2

         - name: Login to Dockerhub
           uses: docker/login-action@v2
           with:
               username: ${{ secrets.HUB_USERNAME }}
               password: ${{ secrets.HUB_PASSWORD }}

         - name: Get the id
           id: run
           run: echo "::set-output name=run_id::${{ github.run_id }}')"

         - name: Build and Push Image
           uses: docker/build-push-action@v2
           with:
            context: .
            tags: kusumaningrat16/bookshelf-be-nodejs:dev-${{ steps.run.outputs.run_id }}

         
      
   main:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
            node-version: '14'
         - run: npm install

