name: 'Docker NodeJS CI/CD'
run-name: Nodejs CI/CD
on: 
 push:
    branches:
        - dev
        - main

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v3
      
         - name: Setup Docker buildx
           id: buildx
           uses: docker/setup-buildx-action@v2

         - name: Login to Dockerhub
           uses: docker/login-action@v2
           with:
               username: ${{ secrets.HUB_USERNAME }}
               password: ${{ secrets.HUB_PASSWORD }}

         - name: Create a tag
           id: tag
           run: |
            echo "::set-output name=date::$(date +%Y%m%d)"
            echo "::set-output name=tag::${{ github.run_id }}"

         - name: Build and Push Image
           uses: docker/build-push-action@v2
           with:
            context: .
            push: true
            tags: kusumaningrat16/bookshelf-be-nodejs:dev-${{ steps.tag.outputs.date }}-${{ steps.tag.outputs.tag }}

   deploy-dev:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/dev'
      steps:
         - name: Deplyoing to devserver
           uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
           with:
            ORIGIN: ${{ secrets.HOST }}
            USER: ${{ secrets.USERNAME}}
            SSHKEY: ${{ secrets.PRIVATE_KEY }}
         
         - run: ssh devops@192.168.10.1 ls --help

   main:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
            node-version: '14'
         - run: npm install

